# Generated by Django 5.2.14 on 2026-06-19 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbookentry',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guestbook_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guestbookentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
