# Generated by Django 5.2.14 on 2026-07-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0002_guestbookentry_author_guestbookentry_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbookentry',
            name='title',
            field=models.CharField(default='제목 없음', max_length=100),
        ),
    ]
