# Generated by Django 5.2.14 on 2026-07-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('color', models.CharField(default='#3788d8', max_length=20)),
            ],
            options={
                'ordering': ['start', 'end'],
            },
        ),
        migrations.AlterModelOptions(
            name='popupnotice',
            options={},
        ),
    ]
